// Generated by CoffeeScript 1.7.1
(function() {
  var Mod_Vim, async, breach, common, express, http;

  breach = require('breach_module');

  common = require('./lib/common.js');

  express = require('express');

  async = require('async');

  http = require('http');

  Mod_Vim = (function() {
    var bootstrap, setup;

    function Mod_Vim() {}

    bootstrap = function(port) {
      breach.init(function() {
        breach.expose('init', (function(src, args, cb_) {
          console.log('mod_vim (Vimperator port for Breach)');
          return console.log("Listening on " + port);
        }));
        return breach.expose('kill', (function(args, cb_) {
          return common.exit(0);
        }));
      });
      return process.on('uncaughtException', (function(err) {
        return common.fatal(err);
      }));
    };

    setup = function() {
      var app, http_srv;
      app = express();
      app.use('/', express["static"](__dirname + '/controls'));
      http_srv = http.createServer(app).listen(0, '127.0.0.1');
      return http_srv.on('listening', (function() {
        var port;
        port = http_srv.address().port;
        return bootstrap(port);
      }));
    };

    setup();

    return Mod_Vim;

  })();

}).call(this);
